version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "slic-watch"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-167xnalzxxva4"
s3_prefix = "slic-watch"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "WatchServices=\"lambda,kinesis,sqs,dynamodb\" TagFilter=\"\""

