AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  slic-watch

  Automatic CloudWatch metrics, alarms and dashboards

Metadata:
  AWS::ServerlessRepo::Application:
    Name: slic-watch
    Description: Automatic CloudWatch metrics, alarms and dashboards
    Author: fourTheorem
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['cloudwatch', 'lambda', 'kinesis', 'dynamodb']
    HomePageUrl: https://github.com/fourTheorem/slic-watch
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/fourTheorem/slic-watch

Parameters:
  WatchServices:
    Type: String
    Description: >
      A comma-separated list of AWS services to watch.
      All supported services are included by default (`lambda`).
    Default: 'lambda'
  TagFilter:
    Type: String
    Description: >
      A filter pattern used to match deployed services to be watched,
      e.g. '(KEY1=VALUE or KEY1=VALUE) and KEY2!=VALUE'
  LambdaErrorsThreshold:
    Type: Number
    Description: >
      The number of errors required to trigger a Lambda errors alarm
    Default: 1
  LambdaErrorsPeriod:
    Type: Number
    Description: >
      The length, in seconds, used each time the Lambda errors metric is evaluated.
      Valid values are 10, 30, and any multiple of 60.
    Default: 60
  LambdaThrottlesRateThreshold:
    Type: Number
    Description: >
      The minimum percentage rate of throttles against invocations to trigger a throttles alarm
    Default: 1

Globals:
  Function:
    Environment:
      Variables:
        POWERTOOLS_LOGGER_LOG_EVENT: true
        POWERTOOLS_TRACE_DISABLED: true
        POWERTOOLS_SERVICE_NAME: slicwatch
        LOG_LEVEL: INFO
        SNS_ALARMS_TOPIC: !Ref SNSAlarmsTopic
        LAMBDA_THROTTLES_RATE_THRESHOLD: !Ref LambdaThrottlesRateThreshold
        LAMBDA_ERRORS_PERIOD: !Ref LambdaErrorsPeriod
        LAMBDA_ERRORS_THRESHOLD: !Ref LambdaErrorsThreshold
        TAG_FILTER: !Ref TagFilter
        WATCH_SERVICES: !Ref WatchServices

Resources:
  HandleStack:
    Type: AWS::Serverless::Function
    Properties:
      Description: Create CloudWatch alarms and dashboards in response to CloudFormation update of this stack
      CodeUri: watch/
      Handler: watch_handler.handle_stack
      Runtime: python3.8
      Timeout: 30
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - cloudwatch:ListMetrics
              - cloudwatch:PutDashboard
              - cloudwatch:PutMetricAlarm
              - cloudwatch:PutMetricData
            Resource: '*'
        - Statement:
            Effect: Allow
            Action:
              - lambda:GetFunction
              - lambda:ListFunctions
            Resource: '*'

  HandleStackLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${HandleStack}
      RetentionInDays: 7

  HandleFunctionCreateUpdate:
    Type: AWS::Serverless::Function
    Properties:
      Description: Create CloudWatch alarms and dashboards in response to Lambda function create or update
      CodeUri: watch/
      Handler: watch_handler.handle_function_create_updates
      Runtime: python3.8
      Timeout: 30
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - cloudwatch:ListMetrics
              - cloudwatch:PutDashboard
              - cloudwatch:PutMetricAlarm
              - cloudwatch:PutMetricData
            Resource: '*'
        - Statement:
            Effect: Allow
            Action:
              - lambda:GetFunction
              - lambda:ListFunctions
            Resource: '*'
      Events:
        CloudTrailTrigger:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.lambda
              detail-type:
                - AWS API Call via CloudTrail
              detail:
                eventSource:
                  - lambda.amazonaws.com
                eventName:
                  - prefix: CreateFunction
                  - prefix: UpdateFunctionConfiguration

  HandleFunctionCreateUpdateLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${HandleFunctionCreateUpdate}
      RetentionInDays: 7

  HandleFunctionDelete:
    Type: AWS::Serverless::Function
    Properties:
      Description: Delete CloudWatch alarms and dashboards in response to Lambda function delete
      CodeUri: watch/
      Handler: watch_handler.handle_function_delete
      Runtime: python3.8
      Timeout: 30
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - cloudwatch:ListMetrics
              - cloudwatch:PutDashboard
              - cloudwatch:PutMetricAlarm
              - cloudwatch:PutMetricData
            Resource: '*'
      Events:
        CloudTrailTrigger:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.lambda
              detail-type:
                - AWS API Call via CloudTrail
              detail:
                eventSource:
                  - lambda.amazonaws.com
                eventName:
                  - prefix: DeleteFunction
                  - prefix: UpdateFunctionConfiguration

  HandleFunctionDeleteLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${HandleFunctionDelete}
      RetentionInDays: 7

  DeleteResources:
    Type: AWS::Serverless::Function
    Properties:
      Description: Remove existing alarms and metrics linked to a deleted resource
      CodeUri: watch/
      Handler: delete_handler.delete_resources
      Runtime: python3.8
      Timeout: 30
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - cloudwatch:DeleteAlarms
              - cloudwatch:DescribeAlarms
            Resource: '*'
        - Statement:
            Effect: Allow
            Action:
              - lambda:GetFunction
            Resource: '*'
      Events:
        CloudTrailTrigger:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.lambda
              detail-type:
                - AWS API Call via CloudTrail
              detail:
                eventSource:
                  - lambda.amazonaws.com
                eventName:
                  - prefix: DeleteFunction

  DeleteResourcesLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${DeleteResources}
      RetentionInDays: 7

  LambdaInvocationCustomResource:
    # This SAR application allows us to invoke Lambda functions
    # on CloudFormation create/update/delete
    # See https://github.com/lumigo-io/SAR-lambdaInvocation-cfn-custom-resource
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:374852340823:applications/lambda-invocation-cfn-custom-resource
        SemanticVersion: 1.4.0

  HandleStackCreate:
    Type: Custom::LambdaInvocation
    DependsOn:
      - HandleStack
      - LambdaInvocationCustomResource
    Properties:
      ServiceToken: !GetAtt LambdaInvocationCustomResource.Outputs.FunctionArn
      FunctionName: !Ref HandleStack
      InvocationType: Event
      When:
        - Create
      Payload:
        Action: Create

  HandleStackDelete:
    Type: Custom::LambdaInvocation
    DependsOn:
      - HandleStack
      - LambdaInvocationCustomResource
    Properties:
      ServiceToken: !GetAtt LambdaInvocationCustomResource.Outputs.FunctionArn
      FunctionName: !Ref HandleStack
      InvocationType: Event
      When:
        - Delete
      Payload:
        Action: Delete

  SNSAlarmsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: SLICWatchAlarms
