version: 2.1

orbs:
  python: circleci/python@0.2.1
  coveralls: coveralls/coveralls@1.0.6

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8-node
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Install Dependencies
          command: make deps
      - run:
          name: Test
          command: make test lint
      - coveralls/upload:
          path_to_lcov: ./.coverage

workflows:
  main:
    jobs:
      - build-and-test
