version: 2.1

orbs:
  python: circleci/python@0.2.1
  coveralls: coveralls/coveralls@1.0.6

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Install Dependencies
          command: |
            pip install -r watch/requirements.txt
            pip install -r watch/requirements-dev.txt
      - run:
          name: Test
          command: |
            PYTHONPATH=watch coverage run -m pytest tests
      - coveralls/upload

workflows:
  main:
    jobs:
      - build-and-test
