version: 2.1

orbs:
  node: circleci/node@2.0.2

workflows:
  workflow:
    jobs:
      - node/test:
          matrix:
            parameters:
              version: ['10.24.0', '12.21.0', '14.6.0']
              app-dir: ['serverless-plugin']
